"""empty message

Revision ID: 3167ca7fa77d
Revises: 
Create Date: 2019-11-12 13:56:45.391989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3167ca7fa77d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=500), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('age', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_Dietetic_index', table_name='Dietetic')
    op.drop_table('Dietetic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dietetic',
    sa.Column('index', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('Nutrition id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('Food name', mysql.TEXT(), nullable=True),
    sa.Column('cuisine', mysql.TEXT(), nullable=True),
    sa.Column('category', mysql.TEXT(), nullable=True),
    sa.Column('Prescribed type', mysql.TEXT(), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Dietetic_index', 'Dietetic', ['index'], unique=False)
    op.drop_table('user')
    op.drop_table('author')
    # ### end Alembic commands ###
